

spring:
  main:
    web-application-type: none

  kafka:
    bootstrap-servers: localhost:29092


  datasource:
    url: jdbc:postgresql://localhost:5432/workflow_db


#No Tomcat,No port needed ,Pure background service{Kafka)
server:
  port: 0

